import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { Square } from "lucide-react";
import { Separator } from "@/components/ui/separator";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const headerMenus = [];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Link href={"/"} className="flex items-center">
          <Square className="size-5 text-muted-foreground" />
          <Square className="size-7" />
          <Square className="size-5 text-muted-foreground" />
        </Link>

        {headerMenus.length !== 0 && (
          <Separator orientation="vertical" className="h-10" />
        )}

        <nav></nav>

        {children}
      </body>
    </html>
  );
}
